# .github/workflows/generate-snake.yml

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:       # Allow manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate the snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: FatemehAsi
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output     # Where the animation files will be published
          build_dir: dist           # Directory containing the output files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
